# Generated by Django 3.1.4 on 2021-01-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210111_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=True, max_length=40),
            preserve_default=False,
        ),
    ]
