# Generated by Django 3.1.4 on 2020-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
