# Generated by Django 3.1.4 on 2020-12-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201222_0548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abouts',
            new_name='About',
        ),
    ]
