# Generated by Django 3.1.4 on 2020-12-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201222_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='headline',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
