# Generated by Django 3.1.4 on 2020-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(),
        ),
    ]
